name: Net
algorithm: dmfanet #
nEpochs: 2000
gpu_mode: True
save_best: True
gpus: [0, 1]
threads: 8

seed: 123
checkpoint: checkpoint
data_dir_train: ./dataset/train/QB-train
data_dir_eval: ./dataset/test_reduced/QB-test
source_ms: ms
source_pan: pan

pretrain:
  pretrained: False
  pre_sr:
  pre_folder: checkpoint

test:
  algorithm: dmfanet #[PANNet, PNN, DIRCNN,PNet,Net,net_v2]
  type: test #[test, eval]
  data_dir: ./dataset/test_full/QB-test
  source_ms: ms
  source_pan: pan
  model: QB/dmfanet_4_20220422/best.pth

data:
  upsacle: 4
  batch_size: 18
  patch_size: 33
  data_augmentation: False
  n_colors: 4
  rgb_range: 255
  normalize: False

schedule:
  lr: 1e-3
  decay: 100 #500
  gamma: 0.1
  optimizer: ADAM #[ADAM, SGD, RMSprop]
  momentum: 0.9 #SGD momentum
  beta1: 0.9 #ADAM beta
  beta2: 0.999 #ADAM beta
  epsilon: 1e-8 #ADAM epsilon
  alpha: 0.9 #RMSprop alpha
  weight_dency: 0
  gclip: 0.04
  loss: MSE #[MSE, L1,SSIM]
  use_YCbCr: False
